import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PHOTO_DIR = path.join(__dirname, '../public/images/photography');
const OUTPUT_FILE = path.join(__dirname, '../src/photography-data.js');

const MONTH_NAMES = {
    '01': 'January', '02': 'February', '03': 'March', '04': 'April',
    '05': 'May', '06': 'June', '07': 'July', '08': 'August',
    '09': 'September', '10': 'October', '11': 'November', '12': 'December'
};

const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png', '.webp', '.gif'];

function parseFolder(folderName) {
    // Expected format: YYYY-MM_Location-Name
    // Example: 2025-12_Sedona-Arizona
    const match = folderName.match(/^(\d{4})-(\d{2})_(.+)$/);
    if (!match) return null;

    const [, year, month, locationRaw] = match;
    const location = locationRaw.replace(/-/g, ' ').replace(/_/g, ', ');
    const date = `${MONTH_NAMES[month]} ${year}`;

    return { year, month, location, date };
}

function getImages(folderPath) {
    const files = fs.readdirSync(folderPath);
    return files
        .filter(file => IMAGE_EXTENSIONS.includes(path.extname(file).toLowerCase()))
        .sort();
}

function getDescription(folderPath) {
    const infoPath = path.join(folderPath, 'info.txt');
    if (fs.existsSync(infoPath)) {
        return fs.readFileSync(infoPath, 'utf-8').trim();
    }
    return '';
}

function scanPhotography() {
    if (!fs.existsSync(PHOTO_DIR)) {
        console.log('Photography directory not found. Creating it...');
        fs.mkdirSync(PHOTO_DIR, { recursive: true });
        return [];
    }

    const folders = fs.readdirSync(PHOTO_DIR, { withFileTypes: true })
        .filter(dirent => dirent.isDirectory())
        .map(dirent => dirent.name);

    const places = [];

    for (const folder of folders) {
        const parsed = parseFolder(folder);
        if (!parsed) {
            console.warn(`Skipping folder "${folder}" - doesn't match format YYYY-MM_Location-Name`);
            continue;
        }

        const folderPath = path.join(PHOTO_DIR, folder);
        const images = getImages(folderPath);

        if (images.length === 0) {
            console.warn(`Skipping folder "${folder}" - no images found`);
            continue;
        }

        const description = getDescription(folderPath);

        places.push({
            year: parsed.year,
            month: parsed.month,
            location: parsed.location,
            date: parsed.date,
            description: description || `Photos from ${parsed.location}`,
            images: images.map(img => `/images/photography/${folder}/${img}`)
        });
    }

    // Sort by date (newest first)
    places.sort((a, b) => {
        const dateA = `${a.year}-${a.month}`;
        const dateB = `${b.year}-${b.month}`;
        return dateB.localeCompare(dateA);
    });

    // Group by year
    const byYear = {};
    for (const place of places) {
        if (!byYear[place.year]) {
            byYear[place.year] = [];
        }
        byYear[place.year].push({
            location: place.location,
            date: place.date,
            description: place.description,
            images: place.images
        });
    }

    // Convert to array sorted by year (newest first)
    const result = Object.entries(byYear)
        .sort(([a], [b]) => b.localeCompare(a))
        .map(([year, places]) => ({ year, places }));

    return result;
}

function generate() {
    console.log('Scanning photography folders...\n');

    const data = scanPhotography();

    const output = `// Auto-generated by scripts/scan-photos.js
// Run "npm run scan-photos" to regenerate

export const photography = ${JSON.stringify(data, null, 4)};
`;

    fs.writeFileSync(OUTPUT_FILE, output);

    console.log(`Found ${data.reduce((sum, y) => sum + y.places.length, 0)} locations across ${data.length} years`);
    console.log(`Generated: src/photography-data.js\n`);

    // Print summary
    for (const yearGroup of data) {
        console.log(`${yearGroup.year}:`);
        for (const place of yearGroup.places) {
            console.log(`  - ${place.location} (${place.images.length} photos)`);
        }
    }
}

generate();
