// Auto-generated by scripts/scan-photos.js
// Run "npm run scan-photos" to regenerate

export const photography = [
    {
        "year": "2025",
        "places": [
            {
                "location": "Sedona Arizona",
                "date": "December 2025",
                "description": "Red rock formations and desert landscapes",
                "images": [
                    "/images/photography/2025-12_Sedona-Arizona/2761766980229_.pic_hd.jpg",
                    "/images/photography/2025-12_Sedona-Arizona/2941767064616_.pic_hd.jpg",
                    "/images/photography/2025-12_Sedona-Arizona/2951767162056_.pic_hd.jpg",
                    "/images/photography/2025-12_Sedona-Arizona/2961767162121_.pic_hd.jpg",
                    "/images/photography/2025-12_Sedona-Arizona/3031767163103_.pic_hd.jpg",
                    "/images/photography/2025-12_Sedona-Arizona/3281767730084_.pic.jpg"
                ]
            }
        ]
    }
];
