export const cards = [
    // ===== PYTHON =====
    {
        id: 'py-gil',
        language: 'Python',
        category: 'Concurrency',
        front: 'What is the GIL?',
        back: 'The Global Interpreter Lock is a mutex in CPython that allows only one thread to execute Python bytecode at a time. CPU-bound multithreading does not get true parallelism. I/O-bound work still benefits because the GIL is released during blocking I/O. Use multiprocessing for CPU parallelism.',
        learn: [
            { heading: 'What', body: 'The Global Interpreter Lock is a mutex inside CPython that lets only one thread execute Python bytecode at a time.' },
            { heading: 'Why it matters', body: 'CPU-bound code does not parallelize with threads, no matter how many cores you have. I/O-bound code still benefits — Python releases the GIL during blocking I/O like network or disk reads.' },
            { heading: 'Watch out', body: 'Reaching for threading to speed up number crunching is the classic mistake. Use multiprocessing (separate processes, no shared GIL), or push the hot path into a native library like NumPy or a C extension.' },
        ],
    },
    {
        id: 'py-mutable-vs-immutable',
        language: 'Python',
        category: 'Data Model',
        front: 'Mutable vs immutable types — examples and why it matters',
        back: 'Immutable: int, float, str, tuple, frozenset, bytes. Mutable: list, dict, set, bytearray, most custom classes. Immutables are hashable (usable as dict keys / set elements). Mutables passed as arguments can be modified by the callee — a common source of bugs.',
        learn: [
            { heading: 'What', body: 'Immutable types (int, float, str, tuple, frozenset, bytes) cannot be changed in place. Mutable types (list, dict, set, bytearray, most custom classes) can.' },
            { heading: 'Why it matters', body: 'Only immutable objects can be dict keys or set elements — they need a stable hash. Mutable objects passed as arguments are aliased: the callee can change them and the caller sees the change.' },
            { heading: 'Watch out', body: 'A "frozen" copy is often what you want for hashable use — tuple(my_list), frozenset(my_set).' },
        ],
    },
    {
        id: 'py-is-vs-eq',
        language: 'Python',
        category: 'Data Model',
        front: '`is` vs `==`',
        back: '`==` calls __eq__ and checks value equality. `is` checks identity (same object in memory). Use `is` only for singletons like None, True, False. Small int caching (-5 to 256) can make `is` appear to work for ints but it is unreliable.',
        learn: [
            { heading: 'What', body: '`==` calls __eq__ to check value equality. `is` checks object identity — whether two variables point to the same object in memory.' },
            { heading: 'Why it matters', body: 'Use `is` for singletons: `x is None`, `x is True`. Use `==` for everything else. The distinction matters whenever value equality and identity diverge.' },
            { heading: 'Watch out', body: 'CPython caches small ints (-5 to 256), so `x is 100` may appear to work but breaks at 257. Never rely on `is` for value comparison.' },
        ],
    },
    {
        id: 'py-mutable-default',
        language: 'Python',
        category: 'Gotchas',
        front: 'Why is `def f(x=[])` dangerous?',
        back: 'Default argument values are evaluated once at function definition time, not at each call. A mutable default is shared across all calls. Idiomatic fix: use None as the default and create a fresh list inside the function.',
        code: 'def f(x=None):\n    if x is None:\n        x = []\n    ...',
        learn: [
            { heading: 'What', body: 'Default argument values are evaluated once — when the function is defined — not at each call.' },
            { heading: 'Why it matters', body: '`def f(x=[])` shares the same list across every call. State accumulates silently and produces bugs that look impossible at first glance.' },
            { heading: 'Watch out', body: 'Use None as the default and create a fresh container inside the function. The same trap applies to dicts and any mutable type.' },
        ],
    },
    {
        id: 'py-legb',
        language: 'Python',
        category: 'Scope',
        front: 'LEGB rule',
        back: 'Name resolution order: Local → Enclosing (any outer function) → Global (module) → Built-in. `global` declares a name as module-level. `nonlocal` declares a name as belonging to the nearest enclosing function scope (used in closures).',
        learn: [
            { heading: 'What', body: 'The order Python searches for a name: Local → Enclosing function → Global (module) → Built-in.' },
            { heading: 'Why it matters', body: 'Tells you where a name comes from in closures and nested scopes. `global x` makes assignment write to module scope; `nonlocal x` makes it write to the nearest enclosing function scope.' },
            { heading: 'Watch out', body: 'Without `global` or `nonlocal`, any assignment inside a function creates a new local variable, silently shadowing outer scope.' },
        ],
    },
    {
        id: 'py-closures',
        language: 'Python',
        category: 'Scope',
        front: 'Closures and `nonlocal`',
        back: 'A closure is an inner function that captures variables from its enclosing scope. By default the inner function can read but not rebind enclosing variables. `nonlocal x` lets the inner function assign to an enclosing-scope x.',
        learn: [
            { heading: 'What', body: 'An inner function that references variables from an enclosing function "closes over" them — the closure keeps those variables alive even after the outer function returns.' },
            { heading: 'Why it matters', body: 'Powerful for decorators, callbacks, and stateful generators. Reading from outer scope works automatically; writing requires `nonlocal`.' },
            { heading: 'Watch out', body: 'In a loop, closures capture variables by reference, not by value at that iteration. Building callbacks in a loop and seeing them all use the final value is the classic bug.' },
        ],
    },
    {
        id: 'py-list-vs-tuple',
        language: 'Python',
        category: 'Data Structures',
        front: 'List vs tuple',
        back: 'List is mutable, tuple is immutable. Tuples are hashable (if their elements are), so they can be dict keys or set elements. Tuples are slightly faster and signal "this collection has fixed structure" — often used as lightweight records.',
        learn: [
            { heading: 'What', body: 'list is a mutable ordered sequence. tuple is immutable. Both support indexing and slicing.' },
            { heading: 'Why it matters', body: 'Tuples are hashable (when their elements are), slightly faster, and signal "fixed structure" — often used as lightweight records or to return multiple values.' },
            { heading: 'Watch out', body: 'A tuple of mutable items is itself immutable, but its contents can change. `(1, [2, 3])` has a hashable head with a mutable tail — and it will break hashing.' },
        ],
    },
    {
        id: 'py-dict-order',
        language: 'Python',
        category: 'Data Structures',
        front: 'Is dict ordered? How is it implemented?',
        back: 'Since Python 3.7 dicts preserve insertion order as a language guarantee. Backed by a hash table; keys must be hashable. Average O(1) lookup/insert. Use collections.OrderedDict only for its extra methods (move_to_end), not for ordering.',
        learn: [
            { heading: 'What', body: 'Since Python 3.7, dicts preserve insertion order as a language guarantee. Backed by a hash table; keys must be hashable; average O(1) lookup and insert.' },
            { heading: 'Why it matters', body: 'You can rely on iteration order matching insertion order — useful for predictable JSON output, deterministic processing, and grouping by first-seen key.' },
            { heading: 'Watch out', body: 'Reach for collections.OrderedDict only when you need its extras (move_to_end, reordering semantics) — not for ordering alone.' },
        ],
    },
    {
        id: 'py-comprehensions',
        language: 'Python',
        category: 'Syntax',
        front: 'List / dict / set comprehensions and generator expressions',
        back: '`[x*2 for x in xs if x>0]` builds a list eagerly. `{k:v for ...}` and `{x for ...}` for dict/set. Parentheses `(x*2 for x in xs)` produce a generator — lazy, one-shot, memory-efficient. Prefer generator expressions for large data.',
        learn: [
            { heading: 'What', body: 'Compact syntax for building collections: list `[x*2 for x in xs if x>0]`, dict `{k: v for ...}`, set `{x for ...}`, and generator expressions `(x*2 for x in xs)`.' },
            { heading: 'Why it matters', body: 'Faster and more readable than equivalent for-loops with .append. Generator expressions are lazy and consume O(1) memory — useful for piping large data through transformations.' },
            { heading: 'Watch out', body: 'Nested comprehensions can read worse than a plain loop. If you need conditional values (not just conditional inclusion), write `[x if cond else y for ...]` — the ternary goes before `for`.' },
        ],
    },
    {
        id: 'py-generators',
        language: 'Python',
        category: 'Iteration',
        front: 'Generators and `yield`',
        back: 'A function containing `yield` returns a generator — an iterator that produces values lazily and remembers state between calls. Each `next()` runs until the next yield. Good for streaming large data, infinite sequences, and pipelines.',
        learn: [
            { heading: 'What', body: 'A function containing `yield` returns a generator — an iterator that produces values one at a time and pauses between them, remembering its state.' },
            { heading: 'Why it matters', body: 'Lets you express streams, infinite sequences, and pipelines that consume O(1) memory regardless of data size. Underpins `for` loops over big inputs.' },
            { heading: 'Watch out', body: 'A generator is one-shot — once exhausted, it cannot be restarted. If you need to iterate twice, store the values in a list or rebuild the generator.' },
        ],
    },
    {
        id: 'py-iterators',
        language: 'Python',
        category: 'Iteration',
        front: 'Iterators vs iterables',
        back: 'Iterable: implements __iter__ (returns an iterator). Iterator: implements __next__ (returns the next value or raises StopIteration). All iterators are iterables (their __iter__ returns self), but not all iterables are iterators (a list is iterable but not an iterator).',
        learn: [
            { heading: 'What', body: 'Iterable = anything with __iter__ that returns an iterator. Iterator = anything with __next__ that returns the next value or raises StopIteration.' },
            { heading: 'Why it matters', body: 'Decouples consumers (for loops, comprehensions) from data producers. Most Python collection APIs accept any iterable, which is what makes them so composable.' },
            { heading: 'Watch out', body: 'Every iterator is an iterable, but a list is iterable yet not an iterator — calling `next()` on a list fails. Use `iter(list)` to get a fresh iterator.' },
        ],
    },
    {
        id: 'py-decorators',
        language: 'Python',
        category: 'Functions',
        front: 'How do decorators work?',
        back: 'A decorator is a callable that takes a function and returns a (usually) replacement function. `@dec` above `def f` is sugar for `f = dec(f)`. Use functools.wraps to preserve the wrapped function\'s name and docstring.',
        code: 'def log(fn):\n    @functools.wraps(fn)\n    def wrapper(*a, **kw):\n        print(fn.__name__)\n        return fn(*a, **kw)\n    return wrapper',
        learn: [
            { heading: 'What', body: 'A callable that takes a function and returns a (usually wrapped) function. `@dec` above `def f` is sugar for `f = dec(f)`.' },
            { heading: 'Why it matters', body: 'Cross-cutting concerns — logging, retry, auth, caching, timing — without polluting the function body. Used heavily in web frameworks (Flask routes, FastAPI dependencies).' },
            { heading: 'Watch out', body: 'Wrappers replace metadata (name, docstring) unless you `@functools.wraps(fn)` the inner wrapper. That matters for debugging, introspection, and doc generators like Sphinx.' },
        ],
    },
    {
        id: 'py-method-decorators',
        language: 'Python',
        category: 'OOP',
        front: '@staticmethod vs @classmethod vs @property',
        back: '@staticmethod: no implicit first arg, just a function in a class\'s namespace. @classmethod: receives the class as first arg (cls) — useful for alternative constructors. @property: turns a method into an attribute access; pair with @x.setter for writes.',
        learn: [
            { heading: 'What', body: '@staticmethod = a plain function in a class\'s namespace, no implicit first arg. @classmethod = receives the class as `cls`, useful for alternative constructors. @property = expose a method as attribute access.' },
            { heading: 'Why it matters', body: '@property lets you swap a public field for computed access without changing any call site. @classmethod is the standard pattern for `from_string`-style factory constructors.' },
            { heading: 'Watch out', body: '@property has a corresponding @x.setter — without it the property is read-only. Adding @x.setter later is a non-breaking change.' },
        ],
    },
    {
        id: 'py-context-managers',
        language: 'Python',
        category: 'Resource Management',
        front: 'Context managers and the `with` statement',
        back: '`with obj as x:` calls obj.__enter__() (binding the return value to x) and guarantees obj.__exit__() runs on exit, even on exception. Used for files, locks, DB transactions. contextlib.contextmanager turns a generator into a context manager.',
        learn: [
            { heading: 'What', body: 'An object implementing __enter__ and __exit__ that can be used in a `with` block. __exit__ runs even when the body raises an exception.' },
            { heading: 'Why it matters', body: 'Guaranteed cleanup for files, locks, DB transactions, temp directories. Replaces brittle try/finally chains and makes intent explicit at the call site.' },
            { heading: 'Watch out', body: 'contextlib.contextmanager turns a generator into a context manager — everything before `yield` is enter, everything after is exit. Standard pattern for setup/teardown in tests.' },
        ],
    },
    {
        id: 'py-dunder',
        language: 'Python',
        category: 'Data Model',
        front: 'What are dunder methods? Name the essential ones.',
        back: 'Double-underscore methods that hook into Python operators and built-ins. Essentials: __init__ (construction), __repr__ (debug string), __eq__ + __hash__ (equality/hashing — must be consistent), __enter__/__exit__ (context managers), __iter__/__next__ (iteration), __len__, __getitem__.',
        learn: [
            { heading: 'What', body: 'Double-underscore methods Python calls implicitly to implement operators and protocols. Essentials: __init__, __repr__, __eq__, __hash__, __len__, __getitem__, __iter__, __enter__/__exit__.' },
            { heading: 'Why it matters', body: 'Lets your classes integrate naturally with the language — be iterable, comparable, hashable, indexable, printable.' },
            { heading: 'Watch out', body: '__eq__ and __hash__ must agree: equal objects must have equal hashes. Override one without the other and dict/set behavior silently breaks.' },
        ],
    },
    {
        id: 'py-exceptions',
        language: 'Python',
        category: 'Errors',
        front: 'try / except / else / finally',
        back: '`try` runs guarded code. `except` catches matching exceptions. `else` runs only if no exception was raised. `finally` always runs (cleanup). Catch specific exception types, not bare `except:` (which also catches KeyboardInterrupt and SystemExit).',
        learn: [
            { heading: 'What', body: '`try` guards code. `except` catches matching exceptions. `else` runs only if no exception was raised. `finally` always runs (cleanup).' },
            { heading: 'Why it matters', body: 'Separating cleanup (finally) from the happy path (else) keeps error handling readable. Catching specific exception types prevents silently swallowing real bugs.' },
            { heading: 'Watch out', body: 'Bare `except:` also catches SystemExit and KeyboardInterrupt — never use it. Use `except Exception:` if you must catch broadly.' },
        ],
    },
    {
        id: 'py-concurrency-models',
        language: 'Python',
        category: 'Concurrency',
        front: 'threading vs multiprocessing vs asyncio — when to use which?',
        back: 'threading: I/O-bound work where you want shared memory (GIL-limited for CPU). multiprocessing: CPU-bound work — separate processes sidestep the GIL but data must be pickled. asyncio: high-concurrency I/O with a single thread and an event loop; requires async-aware libraries.',
        learn: [
            { heading: 'What', body: 'Three different concurrency models. threading uses OS threads sharing memory but limited by the GIL for CPU. multiprocessing uses separate processes — true parallelism but data must be pickled to cross processes. asyncio uses a single thread with an event loop, scaling to many concurrent I/O operations.' },
            { heading: 'Why it matters', body: 'Choosing the wrong model wastes effort or kills performance. Rough rule: many I/O-bound tasks → asyncio; CPU-bound → multiprocessing; modest I/O with shared state → threading.' },
            { heading: 'Watch out', body: 'A blocking call inside asyncio freezes the entire event loop — wrap it with `asyncio.to_thread(...)`. Mixing models gets messy fast.' },
        ],
    },
    {
        id: 'py-async',
        language: 'Python',
        category: 'Concurrency',
        front: 'How do async/await work in Python?',
        back: '`async def` defines a coroutine — calling it returns a coroutine object without running the body. `await` suspends the coroutine until the awaited Awaitable completes; the event loop runs other coroutines meanwhile. Blocking calls (time.sleep, requests) freeze the loop — use async-aware libraries.',
        learn: [
            { heading: 'What', body: '`async def` defines a coroutine. Calling it returns a coroutine object — it does not run the body. `await` suspends until the awaited thing finishes; meanwhile the event loop runs other coroutines.' },
            { heading: 'Why it matters', body: 'Lets a single thread handle thousands of concurrent I/O operations efficiently. Foundation of high-throughput Python web servers and pipelines.' },
            { heading: 'Watch out', body: 'Calling a blocking function — time.sleep, requests.get, sync DB calls — inside an async function blocks the entire loop. Use async-aware libraries (httpx, asyncpg) or push the call into a thread.' },
        ],
    },
    {
        id: 'py-gc',
        language: 'Python',
        category: 'Memory',
        front: 'How does Python manage memory?',
        back: 'CPython uses reference counting — an object is freed when its refcount hits 0. A separate cyclic garbage collector detects and frees reference cycles (e.g., two objects holding each other). `gc` module exposes manual control.',
        learn: [
            { heading: 'What', body: 'CPython tracks how many references point to each object. When the refcount hits zero, the object is freed immediately. A separate cyclic garbage collector handles reference cycles refcounts cannot.' },
            { heading: 'Why it matters', body: 'Most objects die immediately when they go out of scope, which makes Python feel deterministic. Cycles (A.x = B; B.x = A) need the cycle GC to clean up.' },
            { heading: 'Watch out', body: 'weakref helps break cycles for cache-like patterns. __del__ on objects in cycles delays cleanup or, in older Python versions, prevents it entirely.' },
        ],
    },
    {
        id: 'py-slots',
        language: 'Python',
        category: 'Memory',
        front: 'What does `__slots__` do?',
        back: 'Declaring __slots__ = ("x", "y") on a class replaces the per-instance __dict__ with a fixed array, reducing memory and slightly speeding attribute access. Trade-offs: you cannot add new attributes at runtime, and multiple inheritance becomes restricted.',
        learn: [
            { heading: 'What', body: 'A class attribute that declares a fixed set of allowed instance attributes. Replaces the per-instance __dict__ with a compact array.' },
            { heading: 'Why it matters', body: 'Significant memory savings when you have many small instances (millions of records). Slightly faster attribute access too.' },
            { heading: 'Watch out', body: 'No dynamic attribute addition, and multiple inheritance gets restrictive — parents must agree on slots. Use for data classes / DTOs, not general-purpose classes.' },
        ],
    },
    {
        id: 'py-typing',
        language: 'Python',
        category: 'Typing',
        front: 'Type hints — what are the key constructs?',
        back: 'Annotations are runtime-visible but not enforced (use mypy/pyright). Core: `list[int]`, `dict[str, int]`, `Optional[X]` (or `X | None` in 3.10+), `Union`, `Callable`, `TypeVar`, `Protocol` (structural typing / duck typing), `TypedDict` (typed dict shape), `Literal`, `Final`.',
        learn: [
            { heading: 'What', body: 'Optional annotations describing types of variables, parameters, and returns. Visible at runtime but not enforced — checked by tools like mypy or pyright.' },
            { heading: 'Why it matters', body: 'Catches errors before they ship, improves IDE autocomplete, documents intent. Increasingly expected in serious Python codebases.' },
            { heading: 'Watch out', body: 'Core constructs to know: `list[int]`, `dict[str, int]`, `X | None` (3.10+), `Callable[[int], str]`, `Protocol` (structural / duck typing), `TypedDict` (typed dict shape), `Literal`, `Final`.' },
        ],
    },
    {
        id: 'py-duck-typing',
        language: 'Python',
        category: 'OOP',
        front: 'Duck typing',
        back: '"If it walks like a duck and quacks like a duck, it\'s a duck." Python cares about whether an object supports the operations you use on it, not its declared type. EAFP (try/except) is often preferred over LBYL (isinstance checks). Protocols in typing make duck typing checkable statically.',
        learn: [
            { heading: 'What', body: 'An object\'s suitability is determined by whether it has the right methods and attributes, not by its declared type. "If it walks like a duck and quacks like a duck..."' },
            { heading: 'Why it matters', body: 'Makes Python flexible — functions accept anything supporting the operations they use. Aligns with EAFP style (try and handle) over LBYL (check-then-act).' },
            { heading: 'Watch out', body: 'Protocol gives you both duck typing and type safety: declare a Protocol describing the methods you need, and any class implementing them conforms automatically — no inheritance required.' },
        ],
    },
    {
        id: 'py-mro',
        language: 'Python',
        category: 'OOP',
        front: 'MRO and `super()`',
        back: 'Method Resolution Order — the linear order Python searches base classes for a method, computed via C3 linearization. `super()` follows the MRO, not just the immediate parent. Inspect with `ClassName.__mro__`. Cooperative multiple inheritance requires every class to call super().__init__.',
        learn: [
            { heading: 'What', body: 'Method Resolution Order — the linear sequence Python searches for inherited methods, computed via C3 linearization. `super()` follows the MRO, not just the immediate parent.' },
            { heading: 'Why it matters', body: 'Makes multiple inheritance predictable. Inspect with `ClassName.__mro__` to see what order Python will visit base classes.' },
            { heading: 'Watch out', body: 'Cooperative multiple inheritance requires every class in the chain to call `super().__init__(*a, **kw)`. Mixing classes that do and don\'t can drop calls silently.' },
        ],
    },
    {
        id: 'py-args-kwargs',
        language: 'Python',
        category: 'Functions',
        front: '*args and **kwargs',
        back: '*args collects extra positional arguments into a tuple. **kwargs collects extra keyword arguments into a dict. On the call site, `f(*list, **dict)` unpacks them. Used for forwarding arguments to wrapped functions (decorators) and for variadic APIs.',
        learn: [
            { heading: 'What', body: '`*args` collects extra positional arguments into a tuple. `**kwargs` collects extra keyword arguments into a dict. At the call site, `f(*list, **dict)` unpacks them.' },
            { heading: 'Why it matters', body: 'Forwarding arguments through decorators, building flexible APIs, accepting "passthrough" parameters that an inner function will consume.' },
            { heading: 'Watch out', body: 'The names are convention only — `*args, **kwargs` is universally recognized. Renaming them hurts readability for no real gain.' },
        ],
    },
    {
        id: 'py-lambda',
        language: 'Python',
        category: 'Functions',
        front: 'Lambda functions — and their limits',
        back: 'An anonymous one-expression function: `lambda x, y: x + y`. Cannot contain statements or annotations. Idiomatic only for tiny callbacks (e.g. sort keys); for anything more, use a named def for readability.',
        learn: [
            { heading: 'What', body: 'An anonymous one-expression function: `lambda x, y: x + y`. Cannot contain statements, assignments, or annotations.' },
            { heading: 'Why it matters', body: 'Concise for tiny callbacks — sort keys, filter predicates, key in groupby. Avoids defining a one-line function with a name you\'ll never reuse.' },
            { heading: 'Watch out', body: 'For anything beyond a single expression, use a named def — easier to read, easier to debug, supports a docstring. Lambdas should not need explanation.' },
        ],
    },
    {
        id: 'py-modules',
        language: 'Python',
        category: 'Packaging',
        front: 'Modules vs packages, and __init__.py',
        back: 'A module is a single .py file. A package is a directory of modules. __init__.py marks a directory as a regular package and runs on first import (can re-export names). Without it you get a "namespace package" — splittable across paths but with no init code.',
        learn: [
            { heading: 'What', body: 'A module is a single .py file. A package is a directory of modules. __init__.py marks a directory as a regular package and runs on first import.' },
            { heading: 'Why it matters', body: '__init__.py is the standard place to expose a public API via re-exports — control what `from package import X` sees. Without it, you get a namespace package that can be split across paths but has no init code.' },
            { heading: 'Watch out', body: 'Circular imports almost always mean the import structure is wrong. Break the cycle with delayed imports inside functions, or by moving shared code into a third module.' },
        ],
    },

    // ===== C# =====
    {
        id: 'cs-value-vs-ref',
        language: 'C#',
        category: 'Type System',
        front: 'Value types vs reference types',
        back: 'Value types (struct, enum, primitives) hold their data directly; assignment copies the value. Reference types (class, record, string, array, delegate) hold a reference; assignment copies the reference, so both variables point to the same object.',
        learn: [
            { heading: 'What', body: 'Value types (struct, enum, primitives) hold their data directly — assignment copies the value. Reference types (class, record, string, array, delegate) hold a reference to heap memory — assignment copies the reference.' },
            { heading: 'Why it matters', body: 'Determines whether two variables share state. Two variables holding the same reference type see each other\'s mutations. Two value-type copies do not — they\'re independent.' },
            { heading: 'Watch out', body: '`string` is a reference type but feels like a value because it\'s immutable. `int?` and other nullable value types behave like values, with HasValue and Value semantics.' },
        ],
    },
    {
        id: 'cs-stack-heap',
        language: 'C#',
        category: 'Memory',
        front: 'Stack vs heap — where do value and reference types live?',
        back: 'Common simplification: value types live on the stack, reference types on the heap. Reality: value types live wherever they are declared — a struct field of a class lives on the heap, a local int lives on the stack. The real distinction is value vs reference semantics, not storage location.',
        learn: [
            { heading: 'What', body: 'The common simplification: value types on the stack, reference types on the heap. The honest answer: value types live wherever they are declared.' },
            { heading: 'Why it matters', body: 'A struct field of a class lives on the heap, inside the class instance. A local int lives on the stack. A boxed int (assigned to object) lives on the heap. The real distinction is value vs reference semantics, not storage location.' },
            { heading: 'Watch out', body: 'This question often probes whether you parrot the simplification or know the nuance. Mention both in interviews — start with the simple model, then refine.' },
        ],
    },
    {
        id: 'cs-boxing',
        language: 'C#',
        category: 'Type System',
        front: 'Boxing and unboxing',
        back: 'Boxing: wrapping a value type in an object reference on the heap (e.g. assigning int to object). Unboxing: extracting the value back with a cast. Both involve allocation/copy and are slow — avoid in hot paths. Generics (List<int>) eliminated the historical need.',
        learn: [
            { heading: 'What', body: 'Boxing wraps a value type in an object reference on the heap (e.g. assigning int to object). Unboxing extracts the value back via a cast.' },
            { heading: 'Why it matters', body: 'Every box is a heap allocation. In hot paths boxing causes GC pressure and surprising slowdowns.' },
            { heading: 'Watch out', body: 'Generics (List<int>) and Span<T> mostly eliminated the need for boxing. Watch for hidden boxing when calling object.Equals or formatting structs via interpolation/{0}.' },
        ],
    },
    {
        id: 'cs-ref-out-in',
        language: 'C#',
        category: 'Parameters',
        front: 'ref, out, and in parameters',
        back: 'ref: caller must initialize; callee may read and write. out: callee must assign before returning; caller need not initialize. in: pass by reference but read-only (perf for large structs). Without any modifier, value types are copied and reference types pass the reference by value.',
        learn: [
            { heading: 'What', body: 'ref = caller initializes, callee may read and write. out = callee must assign before returning, caller need not initialize. in = pass by reference, read-only (perf for large structs).' },
            { heading: 'Why it matters', body: 'Without any modifier, value types are copied and reference types pass the reference by value. `ref` lets the callee replace the caller\'s variable — common in Try-style methods.' },
            { heading: 'Watch out', body: '`out` is the typical pattern for TryParse / TryGetValue. ref and in are advanced — reach for them when profiling says they matter, not by default.' },
        ],
    },
    {
        id: 'cs-nullable-ref',
        language: 'C#',
        category: 'Type System',
        front: 'Nullable reference types (string?)',
        back: 'Opt-in compile-time feature (since C# 8). Inside an enabled context, `string` means non-null, `string?` means nullable. The compiler tracks flow and warns on possible null dereference. Not a runtime guarantee — values from older libraries can still be null. `!` is the null-forgiving operator.',
        learn: [
            { heading: 'What', body: 'Opt-in compile-time feature (C# 8+). Inside an enabled context, `string` means non-null, `string?` means may be null. The compiler does flow analysis and warns on possible null dereference.' },
            { heading: 'Why it matters', body: 'Catches a huge class of NullReferenceException bugs at compile time. Modern .NET projects enable nullable everywhere.' },
            { heading: 'Watch out', body: 'Not a runtime guarantee. Values from older libraries or JSON deserialization can still be null. The `!` (null-forgiving) operator silences the warning — use sparingly and document why.' },
        ],
    },
    {
        id: 'cs-nullable-value',
        language: 'C#',
        category: 'Type System',
        front: 'Nullable value types (int?)',
        back: 'int? is sugar for Nullable<int>, a struct wrapping a value plus HasValue flag. Access via .Value (throws if null), .HasValue, or ?? for default. Distinct from nullable reference types — int? is a real different type.',
        learn: [
            { heading: 'What', body: 'int? is sugar for Nullable<int> — a struct wrapping a value plus a HasValue flag. Distinct from nullable reference types: int? is a genuinely different type at runtime.' },
            { heading: 'Why it matters', body: 'Lets value types represent "no value" without sentinel hacks like -1 or 0. Common with database results, optional config, missing fields.' },
            { heading: 'Watch out', body: 'Accessing .Value when HasValue is false throws InvalidOperationException. Use ?? for fallback, or pattern matching `is int v` to safely unwrap.' },
        ],
    },
    {
        id: 'cs-generics',
        language: 'C#',
        category: 'Generics',
        front: 'Generics and constraints',
        back: 'Type parameters reified at runtime (not erased like Java). Constraints: `where T : class`, `struct`, `new()` (parameterless ctor), `IComparable<T>`, `notnull`, `unmanaged`. Constraints unlock operations on T inside the generic body.',
        learn: [
            { heading: 'What', body: 'Type parameters that let you write code working with any type while preserving type safety. Reified at runtime — not erased like Java\'s.' },
            { heading: 'Why it matters', body: 'Eliminates the need to cast or box. List<T> vs the old ArrayList is the classic example.' },
            { heading: 'Watch out', body: 'Constraints unlock operations on T: `where T : class`, `struct`, `new()`, `IComparable<T>`, `notnull`, `unmanaged`. Without constraints, T is essentially just `object`.' },
        ],
    },
    {
        id: 'cs-variance',
        language: 'C#',
        category: 'Generics',
        front: 'Covariance and contravariance (in / out)',
        back: 'On interfaces and delegates only. `out T` (covariant): T appears only as output → IEnumerable<Cat> assignable to IEnumerable<Animal>. `in T` (contravariant): T appears only as input → Action<Animal> assignable to Action<Cat>. Invariant by default.',
        learn: [
            { heading: 'What', body: 'Only on interfaces and delegates. `out T` (covariant): T appears only as output → IEnumerable<Cat> can be assigned to IEnumerable<Animal>. `in T` (contravariant): T appears only as input → Action<Animal> can be assigned to Action<Cat>. Everything is invariant by default.' },
            { heading: 'Why it matters', body: 'Lets you pass derived-typed collections to functions expecting base-typed ones, without casting.' },
            { heading: 'Watch out', body: 'Classes cannot be variant. Arrays are technically variant but unsafely so — they can throw at runtime on assignment. Stick to generic collections.' },
        ],
    },
    {
        id: 'cs-gc',
        language: 'C#',
        category: 'Memory',
        front: 'Generational garbage collection',
        back: 'Managed heap split into Gen 0 (new), Gen 1 (survived one GC), Gen 2 (long-lived). Most objects die young, so Gen 0 collections are frequent and cheap. Large Object Heap (LOH, >= 85KB) is collected with Gen 2. Allocation is fast (bump pointer); only collection is expensive.',
        learn: [
            { heading: 'What', body: 'The managed heap is split into Gen 0 (new), Gen 1 (survived one GC), and Gen 2 (long-lived). Most objects die young, so Gen 0 collections are frequent and cheap; Gen 2 is rare and expensive.' },
            { heading: 'Why it matters', body: 'Allocation is essentially free — a bump pointer. It\'s collection that costs. Allocating lots of short-lived garbage in a hot path is usually fine; allocating lots that survives is what hurts.' },
            { heading: 'Watch out', body: 'The Large Object Heap (≥85KB) is collected with Gen 2 — careless large allocations cause big pauses. Pool large buffers (ArrayPool<T>) rather than reallocating.' },
        ],
    },
    {
        id: 'cs-idisposable',
        language: 'C#',
        category: 'Resource Management',
        front: 'IDisposable and the `using` statement',
        back: '`using var x = ...` (or `using (var x = ...)`) calls x.Dispose() at end of scope — deterministic cleanup of unmanaged resources (files, sockets, DB handles). Without it, cleanup waits for the finalizer (if any), which is non-deterministic.',
        learn: [
            { heading: 'What', body: 'An interface with a single Dispose() method. `using var x = ...` (or `using (var x = ...)`) calls Dispose at end of scope automatically.' },
            { heading: 'Why it matters', body: 'Deterministic cleanup for files, sockets, DB connections, locks. Without it, cleanup depends on the finalizer (if any), which runs non-deterministically.' },
            { heading: 'Watch out', body: 'Disposing an IDisposable is the caller\'s responsibility. Forgetting it is one of the most common .NET resource leaks — connection pool exhaustion, file handle starvation.' },
        ],
    },
    {
        id: 'cs-finalizer',
        language: 'C#',
        category: 'Resource Management',
        front: 'Finalizer vs Dispose — when do you need a finalizer?',
        back: 'Only if your class directly owns an unmanaged resource (raw handle, native pointer). Implement the full Dispose pattern: Dispose(true) for both managed+unmanaged, Dispose(false) from the finalizer for unmanaged only, call GC.SuppressFinalize. If you only wrap managed IDisposables, you do NOT need a finalizer.',
        learn: [
            { heading: 'What', body: 'A finalizer (~ClassName) runs on a background thread before the GC reclaims the object — non-deterministic timing.' },
            { heading: 'Why it matters', body: 'You only need a finalizer if your class directly owns an unmanaged resource — a raw native handle, a native pointer. Otherwise relying on Dispose alone is correct and simpler.' },
            { heading: 'Watch out', body: 'The full Dispose pattern (Dispose(bool) plus GC.SuppressFinalize) is the safety-net for the rare case both apply. If you only wrap managed IDisposables, skip the finalizer entirely.' },
        ],
    },
    {
        id: 'cs-async-state-machine',
        language: 'C#',
        category: 'Async',
        front: 'How does async/await actually work?',
        back: 'The compiler rewrites an async method into a state machine. Each await splits the method at that point: register a continuation on the awaited Task, return control to the caller. When the Task completes, the continuation runs (often on a captured SynchronizationContext). Tasks represent the eventual result.',
        learn: [
            { heading: 'What', body: 'The compiler rewrites an async method into a state machine class. Each await splits the method: register a continuation, return control to the caller, resume from the right point when the awaited Task completes.' },
            { heading: 'Why it matters', body: 'This is why "async" is not "threads" — most awaits don\'t use a thread while waiting. A single thread can drive thousands of in-flight async operations.' },
            { heading: 'Watch out', body: 'Each async method allocates a state machine. In tight loops, ValueTask (zero-allocation paths) reduces GC pressure when most calls complete synchronously.' },
        ],
    },
    {
        id: 'cs-configure-await',
        language: 'C#',
        category: 'Async',
        front: 'ConfigureAwait(false) — what and why?',
        back: 'By default, await captures the current SynchronizationContext (e.g. UI thread) and resumes on it after the awaited task completes. ConfigureAwait(false) skips that — the continuation runs on any thread. Library code should use it to avoid forcing callers\' contexts and to prevent deadlocks.',
        learn: [
            { heading: 'What', body: 'Tells `await` not to capture the current SynchronizationContext. By default, the continuation resumes on the captured context (UI thread, classic ASP.NET request thread).' },
            { heading: 'Why it matters', body: 'Library code should use ConfigureAwait(false) — forcing callers\' contexts can deadlock or hurt throughput. ASP.NET Core has no sync context, so it\'s a no-op there.' },
            { heading: 'Watch out', body: 'Application code in UI frameworks usually wants the default (resume on UI thread to update controls safely). Library code wants false. Audit by codebase, not blindly.' },
        ],
    },
    {
        id: 'cs-task-vs-thread',
        language: 'C#',
        category: 'Async',
        front: 'Task vs Thread',
        back: 'Thread is an OS-level thread — expensive to create. Task is a unit of work scheduled on the thread pool (or marked as I/O / long-running). Prefer Task/async — the runtime manages threading efficiently. Use Thread only for specialized needs (dedicated long-running loop with specific priority).',
        learn: [
            { heading: 'What', body: 'Thread is an OS-level thread — expensive to create, fixed cost. Task is a unit of work scheduled on the thread pool, often without holding a thread at all (async I/O).' },
            { heading: 'Why it matters', body: 'Use Task/async for almost everything. Spinning up Threads manually is rarely correct in modern .NET — the thread pool already manages threads efficiently.' },
            { heading: 'Watch out', body: 'Task.Run is for offloading CPU-bound work — don\'t wrap async I/O in Task.Run, it just adds a thread pool hop for no benefit.' },
        ],
    },
    {
        id: 'cs-async-void',
        language: 'C#',
        category: 'Async',
        front: 'Why is `async void` dangerous?',
        back: 'Exceptions from async void cannot be caught by the caller — they bubble up to the SynchronizationContext or crash the process. The caller cannot await it for completion. Use only for event handlers, where void is required. Everywhere else use async Task.',
        learn: [
            { heading: 'What', body: 'An async method declared to return void. Exceptions inside it cannot be caught by the caller — they propagate to the SynchronizationContext, or crash the process. The caller also cannot await it for completion.' },
            { heading: 'Why it matters', body: 'Use only for event handlers, where the signature is forced. Everywhere else use async Task — testable, awaitable, exception-propagatable.' },
            { heading: 'Watch out', body: 'An unhandled async void exception in a server can take down the whole process. This is one of the most common production bug magnets in C#.' },
        ],
    },
    {
        id: 'cs-deadlock',
        language: 'C#',
        category: 'Async',
        front: 'Why does `.Result` / `.Wait()` cause deadlocks in UI/ASP.NET (classic)?',
        back: 'In contexts with a single-threaded SynchronizationContext (UI, classic ASP.NET): the calling thread blocks on Task completion, but the Task\'s continuation needs that same thread to resume. Deadlock. Fix: use await all the way down, or ConfigureAwait(false) in the awaited code.',
        learn: [
            { heading: 'What', body: 'Blocking on an async Task in a single-threaded SynchronizationContext (UI, classic ASP.NET) deadlocks. The thread blocks waiting for the Task; the Task\'s continuation needs that same thread to resume.' },
            { heading: 'Why it matters', body: '"Just block on the async call" is a tempting shortcut that ships bugs to production. The deadlock is silent — the app just hangs.' },
            { heading: 'Watch out', body: 'Fix by awaiting all the way down, or use ConfigureAwait(false) in the awaited code. Sync-over-async only works safely in ASP.NET Core because it has no SynchronizationContext.' },
        ],
    },
    {
        id: 'cs-lock',
        language: 'C#',
        category: 'Concurrency',
        front: 'lock, Monitor, SemaphoreSlim',
        back: '`lock(obj)` is sugar for Monitor.Enter/Exit — mutual exclusion within a process, not async-aware (do not await inside). SemaphoreSlim supports async (WaitAsync) and counted access. Always lock on a private readonly object, never on `this` or a type.',
        learn: [
            { heading: 'What', body: '`lock(obj)` is sugar for Monitor.Enter/Exit — mutual exclusion within a process, not async-aware. SemaphoreSlim supports async (WaitAsync) and counted (>1) access.' },
            { heading: 'Why it matters', body: 'Use lock for synchronous paths. Use SemaphoreSlim when you need to await inside a critical section — `lock` does not allow that.' },
            { heading: 'Watch out', body: 'Lock on a private readonly object — never `this`, never a Type, never a string. External code could lock the same object and create surprise contention or deadlocks.' },
        ],
    },
    {
        id: 'cs-interface-vs-abstract',
        language: 'C#',
        category: 'OOP',
        front: 'Interface vs abstract class',
        back: 'Interface: contract only (until C# 8\'s default interface methods). A class can implement many interfaces. Abstract class: can hold state, constructors, concrete and abstract members; a class can extend only one. Use interfaces for capabilities, abstract classes for shared implementation.',
        learn: [
            { heading: 'What', body: 'Interface = contract only (until C# 8 added default interface methods). Multiple inheritance allowed. Abstract class = can hold state, constructors, concrete and abstract members. Single inheritance only.' },
            { heading: 'Why it matters', body: 'Use interfaces for capabilities ("can do X"), abstract classes for shared implementation ("is a kind of Y").' },
            { heading: 'Watch out', body: 'Default interface methods exist but are rarely the right answer — they fragment the OOP model and confuse readers. Prefer composition or abstract base classes.' },
        ],
    },
    {
        id: 'cs-virtual-override-new',
        language: 'C#',
        category: 'OOP',
        front: 'virtual / override / new',
        back: 'virtual: base method can be overridden. override: derived method participates in polymorphic dispatch. new (method modifier): hides the base method without overriding — dispatch depends on the static type of the reference, often a bug magnet.',
        learn: [
            { heading: 'What', body: 'virtual marks a method as overridable. override redefines it polymorphically. new (modifier) hides the base method — dispatch then depends on the static type of the reference, not the runtime type.' },
            { heading: 'Why it matters', body: '`new` is almost always a bug. It silently breaks polymorphism — calling through a base-typed reference goes to the base method, not the derived one.' },
            { heading: 'Watch out', body: 'When the compiler warns "hides inherited member" without `new`, fix the design — don\'t just add `new` to silence the warning.' },
        ],
    },
    {
        id: 'cs-properties',
        language: 'C#',
        category: 'OOP',
        front: 'Properties vs fields',
        back: 'A property is a pair of get/set methods exposed like a field. Auto-properties (`public int X { get; set; }`) compile to a backing field. init-only setters (`{ get; init; }`) allow assignment only during object initialization. Always expose data through properties — they enable validation, virtualization, and binary compatibility.',
        learn: [
            { heading: 'What', body: 'A property is a get/set method pair exposed like a field. Auto-properties (public int X { get; set; }) compile to a backing field.' },
            { heading: 'Why it matters', body: 'Always expose data through properties — they enable validation, lazy computation, virtualization, and binary compatibility. You can change the implementation without recompiling callers.' },
            { heading: 'Watch out', body: 'init-only setters (`{ get; init; }`) allow assignment only during object initialization — great for immutable-after-construction types without giving up object initializer syntax.' },
        ],
    },
    {
        id: 'cs-records',
        language: 'C#',
        category: 'OOP',
        front: 'Records (C# 9+)',
        back: 'Reference types with value-based equality by default. `record Point(int X, int Y);` generates ctor, properties, Equals, GetHashCode, ToString, and a `with` expression for non-destructive mutation. `record struct` is the value-type variant.',
        learn: [
            { heading: 'What', body: 'Reference types (record) or value types (record struct) with value-based equality by default. `record Point(int X, int Y);` auto-generates constructor, properties, Equals, GetHashCode, ToString, and a `with` expression for non-destructive mutation.' },
            { heading: 'Why it matters', body: 'Immutable data carriers without ceremony. `with` makes "give me a copy with one field changed" trivial and readable.' },
            { heading: 'Watch out', body: 'Records compare by all fields — surprising if you wanted reference equality. Use `record struct` for small value-like types (Point, Money) to avoid heap allocation.' },
        ],
    },
    {
        id: 'cs-pattern-matching',
        language: 'C#',
        category: 'Patterns',
        front: 'Pattern matching — what kinds exist?',
        back: 'Type patterns (`obj is string s`), constant patterns (`x is 0`), relational (`x is >= 10`), property patterns (`p is { X: 0, Y: 0 }`), positional patterns for records/tuples, list patterns (`[1, .., 9]`). Combinable with `and`, `or`, `not`. Used in `is` and `switch` expressions.',
        learn: [
            { heading: 'What', body: 'Type patterns (`obj is string s`), constant patterns (`x is 0`), relational (`x is >= 10`), property patterns (`p is { X: 0, Y: 0 }`), positional patterns for records/tuples, list patterns (`[1, .., 9]`). Combinable with and/or/not.' },
            { heading: 'Why it matters', body: 'Replaces piles of type-check + cast + null-check boilerplate. switch expressions return values directly, making business logic compact and readable.' },
            { heading: 'Watch out', body: 'Deeply nested property patterns can read worse than a few explicit checks. Don\'t pattern-golf at the expense of clarity — match the tool to the situation.' },
        ],
    },
    {
        id: 'cs-delegates',
        language: 'C#',
        category: 'Functions',
        front: 'Delegates, events, Action, Func',
        back: 'A delegate is a typed reference to a method. Func<T1,...,TResult> and Action<T1,...> are built-in generic delegates. An event is a delegate exposed through accessors (add/remove) — callers can subscribe but cannot invoke or reassign. Lambdas (`x => x + 1`) are convertible to compatible delegate types.',
        learn: [
            { heading: 'What', body: 'A delegate is a typed reference to a method. Func<T1,...,TResult> and Action<T1,...> are the built-in generic forms. An event is a delegate exposed through add/remove accessors so callers can subscribe but cannot invoke or replace.' },
            { heading: 'Why it matters', body: 'First-class functions in C#. Lambdas (`x => x + 1`) convert implicitly to compatible delegate types — the basis of LINQ, callbacks, and most async patterns.' },
            { heading: 'Watch out', body: 'Subscribing to an event but never unsubscribing keeps the subscriber alive — classic memory leak in UI frameworks and long-lived event sources. Use weak event patterns or unsubscribe explicitly on dispose.' },
        ],
    },
    {
        id: 'cs-linq-deferred',
        language: 'C#',
        category: 'LINQ',
        front: 'LINQ deferred execution',
        back: 'Most LINQ operators (Where, Select, OrderBy) build an expression and do not execute until enumerated (foreach, ToList, ToArray, First, Count). Re-enumerating a query re-runs it — surprises with side effects or changing data. Materialize once if you need to enumerate multiple times.',
        learn: [
            { heading: 'What', body: 'Most LINQ operators (Where, Select, OrderBy) build a query and do not execute until enumerated — foreach, ToList, ToArray, First, Count, etc.' },
            { heading: 'Why it matters', body: 'Lets you compose queries cheaply. But re-enumerating a query re-runs it, which surprises people with side effects, changing data, or paginated API calls behind the scenes.' },
            { heading: 'Watch out', body: 'Materialize (.ToList()) once if you\'ll enumerate multiple times. Modern Roslyn analyzers catch many multiple-enumeration warnings — pay attention to them.' },
        ],
    },
    {
        id: 'cs-ienumerable-vs-iqueryable',
        language: 'C#',
        category: 'LINQ',
        front: 'IEnumerable vs IQueryable',
        back: 'IEnumerable: in-memory iteration; LINQ operators are delegates run client-side. IQueryable: stores an expression tree; a provider (EF Core, etc.) translates it to SQL and executes on the server. Mixing them carelessly (e.g. .AsEnumerable() too early) fetches everything to memory.',
        learn: [
            { heading: 'What', body: 'IEnumerable = in-memory iteration. LINQ operators run client-side as delegates. IQueryable = stores an expression tree. A provider (EF Core, LINQ-to-SQL) translates that tree to SQL and executes server-side.' },
            { heading: 'Why it matters', body: 'Calling .AsEnumerable() too early in an EF query pulls the entire table into memory, then runs your filter client-side. Suddenly your fast query is N times slower and OOM-prone.' },
            { heading: 'Watch out', body: 'Keep queries on IQueryable as long as you can compose, then materialize at the very end. ToList() at the call site, not in the middle of building a query.' },
        ],
    },
    {
        id: 'cs-equals-gethashcode',
        language: 'C#',
        category: 'OOP',
        front: 'Equals / GetHashCode contract',
        back: 'If a.Equals(b) is true, a.GetHashCode() must equal b.GetHashCode(). GetHashCode must be stable for the lifetime an object is in a hash-based collection — so use immutable fields. Records auto-generate both correctly. Override both together or neither.',
        learn: [
            { heading: 'What', body: 'If a.Equals(b) is true, a.GetHashCode() must equal b.GetHashCode(). The reverse is not required — different objects may share a hash.' },
            { heading: 'Why it matters', body: 'Dictionaries, HashSets, and many algorithms rely on the contract. Violating it causes "duplicates" that mysteriously appear in sets, lookups that miss, and hard-to-reproduce bugs.' },
            { heading: 'Watch out', body: 'GetHashCode must be stable while the object is in a hash-based collection — use immutable fields. Records generate both correctly. For custom classes, override both together (HashCode.Combine helps) or neither.' },
        ],
    },
    {
        id: 'cs-string-stringbuilder',
        language: 'C#',
        category: 'Performance',
        front: 'String immutability and StringBuilder',
        back: 'string is immutable — every concatenation allocates a new string. In a loop, that is O(n^2) and a lot of GC pressure. StringBuilder maintains a mutable buffer and resizes amortized O(1). Use it for loops/large composition; plain `+` and interpolation are fine for short, fixed cases.',
        learn: [
            { heading: 'What', body: 'string is immutable — every `+=` creates a new string and copies the old contents. StringBuilder maintains a mutable resizable buffer and appends in amortized O(1).' },
            { heading: 'Why it matters', body: 'In a loop, repeated string concatenation is O(n²) and allocates a fresh string each iteration — major GC pressure. StringBuilder avoids that entirely.' },
            { heading: 'Watch out', body: 'For short, fixed concatenations, plain `+` or interpolation is fine and reads better. Reach for StringBuilder when there\'s a loop or unknown count.' },
        ],
    },
    {
        id: 'cs-struct-vs-class',
        language: 'C#',
        category: 'Type System',
        front: 'When should you use a struct over a class?',
        back: 'Small (~<= 16 bytes), immutable, logically a single value, short-lived. Examples: Point, DateTime, Guid. Structs avoid heap allocation but copying gets expensive at size, and mutable structs are bug magnets (copies mutate independently). Default to class unless you have a specific reason.',
        learn: [
            { heading: 'What', body: 'struct = value type, class = reference type. struct should be small (around ≤16 bytes), logically a single value, immutable, and short-lived — Point, DateTime, Guid.' },
            { heading: 'Why it matters', body: 'Structs avoid heap allocation but every assignment and parameter pass copies the whole struct. For large structs, the copy cost overtakes the allocation savings.' },
            { heading: 'Watch out', body: 'Mutable structs are bug magnets — modifying a copy doesn\'t modify the original. If you find yourself wanting a mutable struct, you probably want a class. Default to class unless you have a specific reason.' },
        ],
    },
];

export const playgroundMeta = {
    title: 'Programming Language Playground',
    subtitle: 'Two modes — Learn structured notes, or quiz yourself with flashcards.',
};
